spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: false
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  redis:
    host: localhost
    port: 6379
  #    database: 8
  #    jedis:
  #      pool:
  #        max-active: 8
  #        min-idle: 1
  #        max-idle: 1
  #        max-wait: -1
  elasticsearch:
    jest:
      uris:
        # ES
        http://localhost:9200
      read-timeout: 5000
mybatis:
  typeAliasesPackage: com.nightriver.jungle.common.pojo
  mapper-locations: classpath:mapping/*.xml
#七牛云
qiniu:
  accessKey: 4m0UMJhUKqJhbARflthYfPv4n9tgHpjo8xfH2OSN
  secretKey: grwq64DWBbnt_vIBsiXIF6NCECqIbvjRwz2RI8f9
  bucket: jungle
  path: http://poyxf28eo.bkt.clouddn.com
# 打印sql日志
logging:
  level:
    com:
      pqtel:
        pqcloud:
          core:
            dao: debug