server:
  port: 7000
#服务名字
spring:
  application:
    name: jungle-config
  cloud:
    config:
      server:
        git:
          #git 仓库的地址
          uri: https://github.com/hyz951226/jungle.git
          #git 仓库的账号密码
          username:
          password:
          #配置文件所在的目录
          search-paths: /jungle-common/**
      label: master
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.176.128
    port: 5672
    username: root
    password: root
#加入注册中心，实现高可用
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/